ci: Remove cxxstd=14 from clang 3.5 job on GitHub Actions
Despite https://clang.llvm.org/cxx_status.html saying:

  Clang 3.4 and later implement all of the ISO C++ 2014 standard.

The clang 3.5 suffers from the bug in C++14 mode causing failure of
Boost.Filesystem build with:

  error: debug information for auto is not yet supported
  error: debug information for auto is not yet supported

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800483